language: ruby
before_install:
  - sudo apt-get install -qq libfreetype6-dev
rvm:
  - 2.1.7 # travis-ci issue
  - 2.2.4
  - 2.3.0
matrix:
  allow_failures:
    - rvm: ruby-head
script: bundle exec rgot -v --bench .
notifications:
  email: false
before_install: gem install bundler -v 1.11.2
